# Generated by Django 4.0.6 on 2022-07-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='cideda',
            new_name='cidade',
        ),
    ]
