# Generated by Django 4.0.6 on 2022-07-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atracoes',
            new_name='Atracao',
        ),
    ]
