# Generated by Django 4.1.3 on 2023-01-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_rename_atracoes_atracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='idade_minina',
            new_name='idade_minima',
        ),
    ]
